spring.application.name=ms-pedidos360-catalog
server.port=8083


spring.datasource.url=jdbc:mysql://pedidos360-pedidos.cubftnqdncaw.us-east-1.rds.amazonaws.com:3306/db_pedidos?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=Plutonio987
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
