services:
  entra-demo:
    build:
      context: ./entra-demo
      dockerfile: Dockerfile
      args:
        VITE_ENTRA_TENANT_ID: "49551105-7651-4748-a01b-22b28daeb087"
        VITE_SPA_CLIENT_ID: "ab423fd9-e85e-4838-85f1-30521dacdaf7"
        VITE_API_CLIENT_ID: "fa47563a-a68d-4d29-93c1-64bbfab52085"
        VITE_BFF_BASE_URL: "http://54.147.242.194:8080"  # ← IP pública del BFF
    container_name: entra-demo
    ports:
      - "80:80"
    restart: unless-stopped